Part-1: a. Write a program to print Hello World using TensorFlow.
        b. Perform basic Mathematical operations
        

In [ ]:
import tensorflow as tf


In [ ]:
hello= tf.constant("hello world")
print(hello)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [ ]:
print(hello.numpy())

b'hello world'


In [ ]:
a= tf.constant(2)
b= tf.constant(3)
c= tf.constant(5)

In [ ]:
add= tf. add(a,b)
sub= tf.subtract(a,b)
mul= tf.multiply(a,b)
div= tf.divide(a,b)

In [ ]:
print("addition", add.numpy())
print("subtraction", sub.numpy())
print("multiplication", mul.numpy())
print("division", div.numpy())

addition 5
subtraction -1
multiplication 6
division 0.6666666666666666


In [ ]:
mean= tf.reduce_mean([a,b,c])
sum= tf.reduce_sum([a,b,c])

In [ ]:
print("mean", mean.numpy())
print("sum", sum.numpy())

mean 3
sum 10


In [ ]:
matrix1= tf.constant([[1,2],[3,4]])
matrix2= tf.constant([[5,6],[7,8]])
product= tf.matmul(matrix1,matrix2)

In [ ]:
product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [ ]:
product.numpy()

array([[19, 22],
       [43, 50]], dtype=int32)

Part-2: a. Develop a Neural network model by using linear regression
by using single feature
i.    Y = 3X +2,
ii.   Y = 2X,
iii.  Y = 2X-1


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.array([1,2,3,4,5], dtype=np.float32)
y = np.array([5,8,11,14,17], dtype=np.float32)

In [4]:
model = tf.keras.Sequential([
      tf.keras.layers.Dense(1, input_shape=(1,))
      ])


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [6]:
from re import VERBOSE
model.fit(x, y, epochs=100,verbose=0)


In [7]:
X_new = np.array([6,7,8,], dtype=np.float32)
y_new = model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


In [8]:
model.fit(x, y, epochs=100,verbose=0)

In [10]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [11]:
model.fit(x, y, epochs=100,verbose=0)

In [12]:
X_new = np.array([6,7,8,], dtype=np.float32)
y_new = model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


In [13]:
X_new = np.array([6,7,8,], dtype=np.float32)
predictions = model.predict(X_new)  # Store the predictions
print("predictions for {6, 7, 8}:", predictions.squeeze())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
predictions for {6, 7, 8}: [20.13604  23.192966 26.249895]


Part-3. Develop a Neural network model by using linear regression by
using single feature

i. Y = 3X1 + 2X2 + 1



In [14]:
import numpy as np
import tensorflow as tf

In [15]:
x1 = np.array([1, 2, 3, 4, 5], dtype=np.float32)
x2 = np.array([5, 4, 3, 2, 1], dtype=np.float32)
X = np.column_stack((x1, x2))

In [16]:
y = 3 * x1 + 2 * x2 + 1

In [17]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, input_shape=(2,)))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [18]:
model.compile(optimizer='sgd', loss='mean_squared_error')

In [19]:
model.fit(X, y, epochs=500, verbose=0)

In [20]:
X_new = np.array([[6, 0], [7, -1], [8, -2]], dtype=np.float32)

In [21]:
predictions = model.predict(X_new)
print("Predictions for new inputs:", predictions.squeeze())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
Predictions for new inputs: [18.999992 19.99999  20.999989]
